spring:
  application:
    name: fastlink-business-order
  main:
    banner-mode: off
    web-application-type: none

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.abc.business.fastlink.order.service.impl
  protocol:
    name: dubbo
    port: 10012
  provider:
    timeout: 30000
  consumer:
    check: false