#!/bin/bash
cd ${WORKSPACE}

pwd

rm -rf ./dist/

npm set registry http://192.168.31.120:8082/repository/group-npm/

npm install

echo "开始输出前端 静态包...."

npm run build:prod

echo ${version}

docker build -t server01.harbor.com:41443/ruoyi/xx-web-ruoyi:${version} .

echo "已输出镜像，开始推送...."

docker push server01.harbor.com:41443/ruoyi/xx-web-ruoyi:${version}
