server:
  port: 18880
  tomcat:
    accept-count: 3000
spring:
  main:
    banner-mode: off
  application:
    name: abc-backend

abc:
  auth:
    users:
      - username: admin
        password: Admin12345!@#
      - username: anonymous
        password: anonymous
  jwt:
    issuer: abc-backend
