server:
  port: 65500
spring:
  main:
    banner-mode: off
  application:
    name: abc-backend-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.204.101:23306/dev_test?autoReconnect=true&useServerPreparedStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&connectionTimeZone=SERVER
    username: root
    password: Mysql12345
    ##  HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      ### 最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      ### 最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 1000
      ### 连接池名称，默认HikariPool-1
      pool-name: HikariPool(abc-backend)
      ### 连接超时时间:毫秒，小于250毫秒，会被重置为默认值30秒
      connection-timeout: 10000
      ### 连接测试查询
      connection-test-query: SELECT 1
      ### 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 600000
      ### 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短；单位ms
      max-lifetime: 1800000
      ### 自动提交从池中返回的连接，默认值为true
      auto-commit: true

logging:
  level:
    root: debug
