### 应用端口号
server:
  port: 65500

### 应用基础配置
spring:
  application:
    name: abc-excel-import-demo
  main:
    banner-mode: off

### EXCEL导入解析配置项
abc:
  excel:
    rules:
      - template-code: parseExcel
        title-num: 1
        columns: 姓名|string|255|255|name,年龄|string|3|0|age,备注|date|1|255|memo
