server:
  port: 65500
spring:
  application:
    name: abc-excel-import-demo
  main:
    banner-mode: off

abc:
  excel:
    rules:
      - template-code: parseExcel
        title-num: 1
        columns: 姓名|string|255|255|name,年龄|string|3|0|age,备注|date|1|255|memo
