
spring:
  ### 多数据源配置，需要移除默认的Druid 配置
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  ### 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      ### 配置Druid监控
      #druid:
      #stat-view-servlet:
      #enabled: true
      #login-username: admin
    #login-password: 123456
    dynamic:
      # 配置数据库参数
      primary: master
      strict: true
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.204.112:23306/abc_db?autoReconnect=true&useServerPreparedStmts=false&rewriteBatchedStatements=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          poolPingQuery: SELECT NOW()
          poolPingEnabled: true

  ### redis(spring-boot-starter-data-redis)
  redis:
    database: 1
    host: 127.0.0.1
    # password: test123
    port: 6379
    timeout: 5000