server:
  port: 60000

spring:
  application:
    name: abc-business-portal

apollo:
  ### Apollo默认配置
  bootstrap:
    enabled: true
    namespaces: dubbo.yaml

### -Denv=dev -Didc=dev-xx -Dapollo.meta=http://127.0.0.1:8080
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#    qos-port: 22222
#  registry:
#    group: dev-xx
#    protocol: zookeeper
#    address: zookeeper://127.0.0.1:2181
#  protocol:
#    name: dubbo
#    port: 20000
#  #   provider:
#  #     group: dev-xx
#  consumer:
#    # group: dev-xx
#    loadbalance: leastactive
#    check: false
#    timeout: 5000
#    retries: 0
