server:
  port: 19999
spring:
  application:
    name: abc-fastlink-business-portal
  main:
    banner-mode: off
  redis:
    database: 1
    host: 192.168.204.101
    port: 16379
    timeout: 5000

dubbo:
  application:
    name: ${spring.application.name}
    ## Dubbo框架的QoS（Quality of Service）服务
    qos-enable: false
    ## 默认qos-port: 22222
    qos-port: 33333
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
    timeout: 5000
    retries: 0